# Generated by Django 5.0.6 on 2024-08-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_lib', '0003_playlist_cover'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, to='music_lib.song'),
        ),
    ]
