# Generated by Django 5.0.6 on 2024-07-19 14:03

import music_lib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_lib', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=music_lib.models.upload_playlist_cover_to),
        ),
    ]
