# Generated by Django 5.0.6 on 2024-08-27 01:02

import music_lib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_lib', '0003_playlist_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=music_lib.models.upload_artist_thumbnail_to),
        ),
    ]
