# Generated by Django 5.0.6 on 2024-08-27 01:16

import music_lib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_lib', '0004_artist_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=music_lib.models.upload_artist_avatar_to),
        ),
    ]
