# Generated by Django 5.0.6 on 2024-09-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_lib', '0006_song_duration_song_play_count_playevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
